name: Win32

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2


    - name: Build
      run: C:/Windows/Microsoft.NET/Framework64/v3.5/msbuild.exe /m /p:Configuration=Release player-win32/fanplayer.sln
